version: 0.2

phases:
  pre_build:
    commands:
      - "npm install"
  build:
    commands:
      - "node build"
      - "aws s3 sync ./public s3://tdp-prod.poimisto.com --delete --acl public-read --region eu-central-1"
      